"""Public workflow API with dependency-light, lazy domain exports."""

from __future__ import annotations

from importlib import import_module
from typing import Dict, Tuple

from .core.auth import (
    fetch_access_tokens,
    get_books_client,
    get_inventory_client,
    get_sheet_client,
    get_workdrive_client,
)
from .core.exceptions import (
    LedgerParsingError,
    ReconciliationError,
    SchemaValidationError,
    ZohoAuthError,
    ZohoUsableError,
)
from .core.models import DotDict


_LAZY_EXPORTS: Dict[str, Tuple[str, str]] = {
    "sync_customer_numbers": (".customer_registration", "sync_customer_numbers"),
    "CustomerNumberChange": (".customer_registration", "CustomerNumberChange"),
    "CustomerNumberSyncResult": (".customer_registration", "CustomerNumberSyncResult"),
    "register_customer": (".customer_registration", "register_customer"),
    "CustomerRegistrationResult": (".customer_registration", "CustomerRegistrationResult"),
    "CustomerRegistrationError": (".customer_registration", "CustomerRegistrationError"),
    "RmaCreditPolicy": (".polycab_credit_review", "RmaCreditPolicy"),
    "CreditAudit": (".polycab_credit_review", "CreditAudit"),
    "CreditFinding": (".polycab_credit_review", "CreditFinding"),
    "CreditMemoEvidence": (".polycab_credit_review", "CreditMemoEvidence"),
    "CreditCorrectionPlan": (".polycab_credit_review", "CreditCorrectionPlan"),
    "CreditCorrectionResult": (".polycab_credit_review", "CreditCorrectionResult"),
    "CreditCorrectionError": (".polycab_credit_review", "CreditCorrectionError"),
    "review_polycab_vendor_credits": (".polycab_credit_review", "review_polycab_vendor_credits"),
    "build_credit_correction_plan": (".polycab_credit_review", "build_credit_correction_plan"),
    "execute_credit_correction": (".polycab_credit_review", "execute_credit_correction"),
    "fetch_trial_balance_for_firm": (".audited_financials", "fetch_trial_balance_for_firm"),
    "fetch_trial_balance_for_gstin": (".audited_financials", "fetch_trial_balance_for_gstin"),
    "compare_audited_financials": (".audited_financials", "compare_audited_financials"),
    "ComparisonPeriod": (".audited_financials", "ComparisonPeriod"),
    "ComparisonResult": (".audited_financials", "ComparisonResult"),
    "CustomerValidationReport": (".customer_validation", "CustomerValidationReport"),
    "ContactValidation": (".customer_validation", "ContactValidation"),
    "ValidationIssue": (".customer_validation", "ValidationIssue"),
    "PaymentSeriesSummary": (".payment_inspection", "PaymentSeriesSummary"),
    "CustomerValidator": (".customer_validation", "CustomerValidator"),
    "create_sales_order_from_yaml": (".sales_order_import", "create_sales_order_from_yaml"),
    "parse_invoice_yaml": (".sales_order_import", "parse_invoice_yaml"),
    "InvoiceData": (".sales_order_import", "InvoiceData"),
    "InvoiceLine": (".sales_order_import", "InvoiceLine"),
    "ItemCreationPolicy": (".sales_order_import", "ItemCreationPolicy"),
    "SalesOrderImportError": (".sales_order_import", "SalesOrderImportError"),
    "RenumberPlan": (".payment_renumbering", "RenumberPlan"),
    "RenumberResult": (".payment_renumbering", "RenumberResult"),
    "RenumberingError": (".payment_renumbering", "RenumberingError"),
    "build_renumber_plan": (".payment_renumbering", "build_renumber_plan"),
    "execute_renumbering": (".payment_renumbering", "execute_renumbering"),
    "get_target_payments": (".payment_renumbering", "get_target_payments"),
    "extract_series_info": (".payment_inspection", "extract_series_info"),
    "fetch_customer_payments": (".payment_inspection", "fetch_customer_payments"),

    "CustomerInvoicePaymentReview": (".customer_invoice_payment_review", "CustomerInvoicePaymentReview"),
    "InvoicePaymentRow": (".customer_invoice_payment_review", "InvoicePaymentRow"),
    "PaymentAllocationRow": (".customer_invoice_payment_review", "PaymentAllocationRow"),
    "review_customer_invoices_payments": (".customer_invoice_payment_review", "review_customer_invoices_payments"),
    "invoice_discount_percentage": (".customer_invoice_payment_review", "invoice_discount_percentage"),
    "PaymentMove": (".inter_location_payment_updates", "PaymentMove"),
    "plan_customer_payment_moves": (".inter_location_payment_updates", "plan_customer_payment_moves"),
    "apply_customer_payment_move": (".inter_location_payment_updates", "apply_customer_payment_move"),
    "submit_customer_payment_move": (".inter_location_payment_updates", "submit_customer_payment_move"),
    "verify_customer_payment_batch": (".inter_location_payment_updates", "verify_customer_payment_batch"),
    "VendorPaymentMove": (".inter_location_vendor_payment_proposals", "VendorPaymentMove"),
    "propose_vendor_payment_moves": (".inter_location_vendor_payment_proposals", "propose_vendor_payment_moves"),
    "sync_account_catalog": (".books_account_catalog", "sync_account_catalog"),
    "refresh_mapping_account_names": (".books_account_catalog", "refresh_mapping_account_names"),
    "StatementMapping": (".books_statement_sheet", "StatementMapping"),
    "StatementPeriod": (".books_statement_sheet", "StatementPeriod"),
    "EquityMapping": (".books_statement_sheet", "EquityMapping"),
    "prepare_statement_sheet_updates": (".books_statement_sheet", "prepare_updates"),
    "prepare_equity_updates": (".books_statement_sheet", "prepare_equity_updates"),
    "BillUpdateResult": (".bill_updates", "BillUpdateResult"),
    "BillPostingDateResult": (".bill_updates", "BillPostingDateResult"),
    "update_bill_transaction_posting_date": (".bill_updates", "update_bill_transaction_posting_date"),
    "update_bill_with_payment_reallocation": (".bill_updates", "update_bill_with_payment_reallocation"),
    "CollectionReconciler": (".collection_reconciliation", "CollectionReconciler"),
    "CollectionReconciliationConfig": (".collection_reconciliation", "CollectionReconciliationConfig"),
    "OnlinePaymentReviewConfig": (".collection_reconciliation", "OnlinePaymentReviewConfig"),
    "OnlinePaymentReviewService": (".collection_reconciliation", "OnlinePaymentReviewService"),
    "REQUIRED_OAUTH_SCOPES": (".collection_reconciliation", "REQUIRED_OAUTH_SCOPES"),
    "missing_oauth_scopes": (".collection_reconciliation", "missing_oauth_scopes"),
    "reconcile_collections": (".collection_reconciliation", "reconcile_collections"),
    "check_vendor_credits_location": (".polycab_credit_memos.processor", "check_vendor_credits_location"),
    "create_vendor_credit_from_pdf": (".polycab_credit_memos.processor", "create_vendor_credit_from_pdf"),
    "parse_polycab_credit_memo": (".polycab_credit_memos.processor", "parse_polycab_credit_memo"),
    "process_polycab_credit_memos": (".polycab_credit_memos.processor", "process_polycab_credit_memos"),
    "upload_to_workdrive": (".polycab_credit_memos.processor", "upload_to_workdrive"),
    "upload_vendor_credit_attachment": (".polycab_credit_memos.processor", "upload_vendor_credit_attachment"),
    "import_polycab_rso_pdf": (".polycab_rso", "import_polycab_rso_pdf"),
    "parse_polycab_rso_pdf": (".polycab_rso", "parse_polycab_rso_pdf"),
    "clean_ledger_file": (".vendor_ledger_reconciliation.cleaner", "clean_ledger_file"),
    "get_ledger_metadata": (".vendor_ledger_reconciliation.cleaner", "get_ledger_metadata"),
    "match_bank_with_vendor_ledger": (".bank_vendor_ledger_matching.matcher", "match_bank_with_vendor_ledger"),
    "match_ledger_entries": (".bank_vendor_ledger_matching.matcher", "match_ledger_entries"),
    "reconcile_vendor": (".vendor_ledger_reconciliation.matcher", "reconcile_vendor"),
    "reconcile_vendor_account": (".vendor_ledger_reconciliation.matcher", "reconcile_vendor_account"),
    "consolidate_zeiss_statements": (".vendor_ledger_reconciliation.zeiss_pdf", "consolidate_zeiss_statements"),
    "parse_zeiss_pdf_statement": (".vendor_ledger_reconciliation.zeiss_pdf", "parse_zeiss_pdf_statement"),
    "GSTR1VerificationConfig": (".gstr1_verification", "GSTR1VerificationConfig"),
    "GSTR1Verifier": (".gstr1_verification", "GSTR1Verifier"),
    "verify_gstr1": (".gstr1_verification", "verify_gstr1"),
    "DuplicatePaymentChecker": (".duplicate_payment_check", "DuplicatePaymentChecker"),
    "check_duplicate_payments": (".duplicate_payment_check", "check_duplicate_payments"),
    "CreatorCustomerSyncConfig": (".creator_customer_sync", "CreatorCustomerSyncConfig"),
    "CreatorCustomerSyncer": (".creator_customer_sync", "CreatorCustomerSyncer"),
    "sync_creator_customers": (".creator_customer_sync", "sync_creator_customers"),
    "CreatorBeatAllocationService": (".creator_beat_allocation", "CreatorBeatAllocationService"),
    "CreatorCustomerDeleteSyncConfig": (".creator_customer_delete_sync", "CreatorCustomerDeleteSyncConfig"),
    "CreatorCustomerDeleteSyncer": (".creator_customer_delete_sync", "CreatorCustomerDeleteSyncer"),
    "sync_creator_customer_deletions": (".creator_customer_delete_sync", "sync_creator_customer_deletions"),
    "NeosealItemAuditor": (".neoseal_audit", "NeosealItemAuditor"),
    "audit_neoseal_items": (".neoseal_audit", "audit_neoseal_items"),
    "fetch_neoseal_stock_count": (".neoseal_stock_count", "fetch_neoseal_stock_count"),
    "CreatorBooksPaymentLinkBackfill": (".creator_books_payment_link", "CreatorBooksPaymentLinkBackfill"),
    "BackfillConfig": (".creator_books_payment_link", "BackfillConfig"),
    "CustomerPaymentDateChecker": (".customer_payment_date_check", "CustomerPaymentDateChecker"),
    "check_customer_payment_dates": (".customer_payment_date_check", "check_customer_payment_dates"),
}


def __getattr__(name: str):
    target = _LAZY_EXPORTS.get(name)
    if target is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module_name, attribute_name = target
    try:
        module = import_module(module_name, __name__)
    except ModuleNotFoundError as exc:
        if exc.name in {"pdfplumber", "xlrd", "openpyxl", "dotenv"}:
            raise ModuleNotFoundError(
                f"Workflow {name!r} requires optional dependencies; install "
                "zoho-sdk[workflows]."
            ) from exc
        raise
    value = getattr(module, attribute_name)
    globals()[name] = value
    return value


def __dir__():
    return sorted(set(globals()) | set(_LAZY_EXPORTS))

__all__ = [
    "sync_customer_numbers", "CustomerNumberChange", "CustomerNumberSyncResult",
    "register_customer", "CustomerRegistrationResult", "CustomerRegistrationError",
    "RmaCreditPolicy", "CreditAudit", "CreditFinding", "CreditMemoEvidence", "CreditCorrectionPlan",
    "CreditCorrectionResult", "CreditCorrectionError", "review_polycab_vendor_credits",
    "build_credit_correction_plan", "execute_credit_correction",
    "CustomerValidationReport",
    "ContactValidation",
    "ValidationIssue",
    "PaymentSeriesSummary",
    "CustomerValidator",
    "create_sales_order_from_yaml",
    "parse_invoice_yaml",
    "InvoiceData",
    "InvoiceLine",
    "ItemCreationPolicy",
    "SalesOrderImportError",
    "RenumberPlan",
    "RenumberResult",
    "RenumberingError",
    "build_renumber_plan",
    "execute_renumbering",
    "get_target_payments",
    "extract_series_info",
    "fetch_customer_payments",
    "StatementMapping",
    "StatementPeriod",
    "EquityMapping",
    "prepare_statement_sheet_updates",
    "prepare_equity_updates",
    "sync_account_catalog",
    "refresh_mapping_account_names",
    "BillUpdateResult",
    "BillPostingDateResult",
    "update_bill_transaction_posting_date",
    "update_bill_with_payment_reallocation",
    "fetch_access_tokens",
    "get_books_client",
    "get_inventory_client",
    "get_sheet_client",
    "get_workdrive_client",
    "ZohoUsableError",
    "ZohoAuthError",
    "LedgerParsingError",
    "ReconciliationError",
    "SchemaValidationError",
    "DotDict",
    "clean_ledger_file",
    "get_ledger_metadata",
    "match_ledger_entries",
    "match_bank_with_vendor_ledger",
    "reconcile_vendor_account",
    "reconcile_vendor",
    "parse_zeiss_pdf_statement",
    "consolidate_zeiss_statements",
    "parse_polycab_credit_memo",
    "create_vendor_credit_from_pdf",
    "upload_vendor_credit_attachment",
    "upload_to_workdrive",
    "process_polycab_credit_memos",
    "check_vendor_credits_location",
    "parse_polycab_rso_pdf",
    "import_polycab_rso_pdf",
    "CollectionReconciler",
    "CollectionReconciliationConfig",
    "reconcile_collections",
    "OnlinePaymentReviewConfig",
    "OnlinePaymentReviewService",
    "REQUIRED_OAUTH_SCOPES",
    "missing_oauth_scopes",
    "GSTR1VerificationConfig",
    "GSTR1Verifier",
    "verify_gstr1",
    "DuplicatePaymentChecker",
    "check_duplicate_payments",
    "CreatorCustomerDeleteSyncConfig",
    "CreatorCustomerDeleteSyncer",
    "sync_creator_customer_deletions",
    "NeosealItemAuditor",
    "audit_neoseal_items",
    "fetch_neoseal_stock_count",
    "CreatorBooksPaymentLinkBackfill",
    "BackfillConfig",
    "CustomerPaymentDateChecker",
    "check_customer_payment_dates",
    "GSTCashLedgerCheck",
    "check_gst_cash_ledger",
    "fetch_gst_cash_ledger_report",
]

from .gst_cash_ledger import GSTCashLedgerCheck, check_gst_cash_ledger, fetch_gst_cash_ledger_report
from .gst_monthly import MonthlyGSTCheck, check_monthly_gst, gst_movements, month_bounds
__all__ += ['MonthlyGSTCheck', 'check_monthly_gst', 'gst_movements', 'month_bounds']
